# Generated by Django 5.2.6 on 2025-09-24 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_registro_delete_aluno_delete_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identificador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID',)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.registro')),
            ],
        ),
    ]
